### ISSUE TITLE
Add background image to the hero section

### ISSUE THREAD

**Issue by N-Shar-ma** [N-Shar-ma/FOSS-Weekend-Klox-Website#1]
The topmost section of the website looks pretty plain, doesn't it? Adding a background image to the hero section, can enhance the page immensely, so that's what you have to do to fix this issue!

In the SVG folder, you'll see a `bgImg.svg` file, which is the image you have to use as the background for the section with the hero class (Pro tip: open dev tools in your browser and use ctrl+f to search for `.hero` to easily locate the desired html element!)

Additionally, ensure that the background `cover`s the entire section (and is not `contain`ed in it), and that it is `center`ed. Notice how all elements in the page have curved edges? Make sure this background image too follows the same consistent style of rounded borders. Experiment with values for border radius to see what looks best!

Attach a screenshot showing the new hero section, both for PC and mobile view.

Visual changes are much easier for PR reviewers when the contributor adds screenshots / gifs, as appropriate, which show the change at a cursory glance, so make this a habit!

**Comment by Animeshz** [comment]
I think I can do this, can I be assigned?

**Comment by ghost** [comment]
Can I be assigned this issue?
<img width="1120" alt="1" src="https://user-images.githubusercontent.com/96474794/157804358-87467f22-79a4-4ddc-85c1-a8fd512f078c.png">
<img width="227" alt="2" src="https://user-images.githubusercontent.com/96474794/157804363-e54d7ff4-e356-412e-8508-3eb7b78d0b46.png">

**Comment by N-Shar-ma** [comment]
@Animeshz (sorry for late response) and @delClg Go ahead both of you!

**Comment by KarthikS373** [comment]
Sir is this still available to be assigned
?

**Comment by N-Shar-ma** [comment]
@KarthikS373 It's ma'am, not sir. And yes you can work on this

**Comment by g-kabra** [comment]
Ma'am can I work on this ( ._.)

**Comment by deep-69bits** [comment]
mamm can i work on this

**Comment by N-Shar-ma** [comment]
@AlphaGaurav7 Yes you can. Sorry @deep, we already have enough people working on this :/ But if within 3 hours gaurav or karthik are unable to have a PR accepted, you can pick this up then!

**Comment by KarthikS373** [comment]
Corrected the PR issue number #1 
https://github.com/N-Shar-ma/FOSS-Weekend-Klox-Website/pull/12#issue-1166076481

**Comment by deep-69bits** [comment]
cani work on it?? now

**Comment by N-Shar-ma** [comment]
@deep-69bits Sorry, the 1st 3 assignees solved the issue in time. Hope to see you fix something else!
