### ISSUE TITLE
Detect dark mode automatically from user's browser or system settings

### ISSUE THREAD

**Issue by N-Shar-ma** [N-Shar-ma/FOSS-Weekend-Klox-Website#15]
The dark mode toggle is a great convenience for users to make the page look as they would prefer. However, these days, websites are even smarter and predict when the user might want the website to be in dark mode based on the browser / system settings, and display the website directly in the desired mode without the need for a toggle.

To solve this issue your task is to make changes to the CSS file for dark mode, so that it directly detects if the user prefers a dark color scheme and accordingly sets the mode of the website. Also remove the toggle (just removing the markup for it from the html would be enough for this task)

Here are a couple hints: 
- You'll need to use the `darkable` class on the body, and won't need to use the `dark` class anymore
- If you have no idea how to detect user's preferred colour scheme in CSS... just Google that! 😉

**Comment by deep-69bits** [comment]
CAN I DO THIS

**Comment by deep-69bits** [comment]
Can I try this

**Comment by Ilikepizza2** [comment]
I'd like to be assigned this issue

**Comment by N-Shar-ma** [comment]
@deep-69bits @Ilikepizza2 You have 3 hours from now!

**Comment by laveshverma007** [comment]
Maam can you assign this to me?

**Comment by N-Shar-ma** [comment]
@laveshverma007 You're assigned too, go ahead!

**Comment by superiorsd10** [comment]
@N-Shar-ma Ma'am! I think I acquire enough knowledge to resolve this issue, so please consider assigning this to me.

**Comment by N-Shar-ma** [comment]
@superiorsd10 Sorry, 3 people are already working on this, but if anyone fails to make a successful PR within the time limit you can definitely take this up!
