### ISSUE TITLE
Fix the hamburger menu icon in mobile view

### ISSUE THREAD

**Issue by N-Shar-ma** [N-Shar-ma/FOSS-Weekend-Klox-Website#2]
Do you see how the hamburger menu icon (yes, that's what the icon with 3 stacked horizontal lines is commonly called) looks a little odd when it is toggled to show the dropdown menu on mobile? It certainly would look better if the middle line were to disappear when the other 2 transition to form a cross.

To fix this issue, make the middle line of the hamburger menu icon disappear when toggled, and reappear when the dropdown is closed. Make sure the transition is smooth and not abrupt. Also, notice how the relevant CSS is structured and try to keep all related code together in a logical fashion. That is, don't just tack on new CSS rules at the end of the file!

Attach a gif showing the new complete animation for the hamburger menu icon.

Visual changes are much easier for PR reviewers when the contributor adds screenshots / gifs, as appropriate, which show the change at a cursory glance, so make this a habit!

**Comment by ArpitaJJ** [comment]
ma'am can you pls assign me this

**Comment by Umm-E-Kulsum** [comment]
could you please assign this issue to me ma'am

**Comment by divya-nshi** [comment]
ma'am i would like to work on this issue

**Comment by N-Shar-ma** [comment]
@ArpitaJJ @Umm-E-Kulsum @divya-nshi All 3 of you have 3 hours from now to solve this issue, consider yourself assigned!

**Comment by deep-69bits** [comment]
can u please assign these to me to??

**Comment by g-kabra** [comment]
I'd like to resolve this issue as well, please assign!

**Comment by N-Shar-ma** [comment]
@deep-69bits @AlphaGaurav7 Sorry this issue has already been taken up and successfully solved by 3 people. Do give other free issues a try!
