### ISSUE TITLE
Improve the behaviour of auto-scrolling links

### ISSUE THREAD

**Issue by N-Shar-ma** [N-Shar-ma/FOSS-Weekend-Klox-Website#3]
Every movement in our website is nice and smooth, but the navigation links at the top and the "Back To Top" button abruptly scroll the page. That looks very jarring, doesn't it? Also it doesn't seem to scroll up the page exactly to the destination and hides a bit of its top part under the header (to verify this, check that the heading "Products" is half hidden under the header, when you click on its link in the navigation bar)

To fix this issue, make sure all scrolling in the page is smooth. Also make sure that the tops of the destination to be scrolled into view are not hidden by the header (pro tip: there is a very little known CSS property "scroll-padding-top" that'll help!)

Attach a gif showing the new scrolling behaviour on clicking any of the navigation links or the "Top To Bottom" button.

Visual changes are much easier for PR reviewers when the contributor adds screenshots / gifs, as appropriate, which show the change at a cursory glance, so make this a habit!

**Comment by ArpitaJJ** [comment]
ma'am pls assign me this

**Comment by divya-nshi** [comment]
Ma'am i would like to be assigned to resolve this issue

**Comment by Ilikepizza2** [comment]
Ma'am I'd also like to be assigned this issue

**Comment by N-Shar-ma** [comment]
@divya-nshi @Ilikepizza2 Go ahead, you both have 3 hours from now to make a PR

**Comment by ghost** [comment]
Can I work on this issue?

https://user-images.githubusercontent.com/96474794/157805864-a28c6dde-aadc-48e2-b11e-79d003ef0850.mp4

**Comment by N-Shar-ma** [comment]
@delClg Sure, make the PR!

**Comment by Perumallpardhiv** [comment]
Ma'am I would like to resolve this issue.

**Comment by N-Shar-ma** [comment]
@Perumallpardhiv Sorry we already have 3 timely PRs. Hope to see you claim other free issues!

**Comment by deep-69bits** [comment]
can i work on this
